### ISSUE TITLE
Doesn't recognise Selenocysteine in query protein sequences. 

### ISSUE THREAD

**Issue by grayfall** [nathanweeks/exonerate#5]
Hello. I'm trying to run the latest release version of exonerate while some of my query sequences contain selenocysteine (U). The tool was compiled with no custom configuration flags on the latest Ubuntu release.  I'm getting this error. 

> *\* FATAL ERROR **: Unknown amino acid [U]
> exiting ...

The command I used to start the process

`nohup exonerate -q prot/* -t gen/* -Q protein -T dna -m protein2genome --percent 50 --showtargetgff -n 1 --maxintron 50000 --cores 1 > out.gff &`

Here are the faulty sequences from the `prot` directory

`cat prot/*.fna | grep -v -e "^>" | grep "U"`

> MVYISNGQVLDSRSQSPWRLSLITDFFWGIAEFVVLFFKTLLQQDVKKRRSYGNSSDSRYDDGRGPPGNPPRRMGRINHLRGPSPPPMAGGUGR
> MAEASATGACGEAMAAAEGSSGPAGLTLGRSFSNYRPFEPQALGLSPSWRLTGFSGMKGUGCKVPQEALLKLLAGLTRPDVRPPLGRGLVGGQEEASQEAGLPAGAGPSPTFPALGIGMDSCVIPLRHGGLSLVQTTDFFYPLVEDPYMMGRIACANVLSDLYAMGITECDNMLMLLSVSQSMSEEEREKVTPLMVKGFRDAAEEGGTAVTGGQTVVNPWIIIGGVATVVCQPNEFIMPDSAVVGDVLVLTKPLGTQVAVNAHQWLDNPERWNKVKMVVSREEVELAYQEAMFNMATLNRTAAGLMHTFNAHAATDITGFGILGHSQNLAKQQRNEVSFVIHNLPIIAKMAAVSKASGRFGLLQGTSAETSGGLLICLPREQAARFCSEIKSSKYGEGHQAWIVGIVEKGNRTARIIDKPRVIEVLPRGATAAVLAPDSSNASSEPSS
> MAAMAVALRGLGGRFRWRTQAVAGGVRGAARGAAAGQRDYDLLVVGGGSGGLACAKEAAQLGRKVAVVDYVEPSPQGTRWGLGGTCVNVGCIPKKLMHQAALLGGLIQDAPNYGWEVAQPVPHDWRKMAEAVQNHVKSLNWGHRVQLQDRKVKYFNIKASFVDEHTVCGVAKGGKEILLSADHIIIATGGRPRYPTHIEGALEYGITSDDIFWLKESPGKTLVVGASYVALECAGFLTGIGLDTTIMMRSIPLRGFDQQMSSMVIEHMASHGTRFLRGCAPSRVRRLPDGQLQVTWEDSTTGKEDTGTFDTVLWAIGRVPDTRSLNLEKAGVDTSPDTQKILVDSREATSVPHIYAIGDVVEGRPELTPIAIMAGRLLVQRLFGGSSDLMDYDNVPTTVFTPLEYGCVGLSEEEAVARHGQEHVEVYHAHYKPLEFTVAGRDASQCYVKMVCLREPPQLVLGLHFLGPNAGEVTQGFALGIKCGASYAQVMRTVGIHPTCSEEVVKLRISKRSGLDPTVTGCUG

Best Regards

**Comment by nathanweeks** [comment]
Sorry for the slow response; I recently got back from travel.
I checked the exonerate 2.4.0 code, and it looks like 1) selenocysteine (U) should be parsed fine, and 2) the three-letter abbreviation appears in a list of amino acids ("Sec"), but 3) the substitution matrices may treat it as a stop codon.

I'm not seeing the error message when I try a query sequence with containing a "U", however; could you verify that you're using either the 2.4.0 release from this git repository, or the development branch (see the instructions in the README file). If you are, could you please provide a target sequence so I can attempt to reproduce the error?

**Comment by dukecomeback** [comment]
Dear nathanweeks, I'm using exonerate 2.4.0 and I've also got this error message "** FATAL ERROR **: Unknown amino acid [U]    exiting ... "
Don't know what's going on.
      Sincerely,
             Kang

**Comment by nathanweeks** [comment]
Sorry for letting this sit on the back burner for so long. Another user just reported this same error, and I was able to reproduce it. I committed a small patch that appears to resolve the issue (allowing Exonerate to correctly identify selenocysteine) to the Exonerate "develop" branch, without affecting how Exonerate handles this amino acid internally (which it apparently scores as cysteine in its substitution matrices---same as BLAST+ since version 2.4.0).

Any testing & experience reporting would be appreciated!

**Comment by xiekunwhy** [comment]
Hi,

I still get this error when I use latest conda version
/software/anaconda3/envs/exonerate/bin/exonerate
exonerate from exonerate version 2.4.0
Using glib version 2.70.2
Built on Feb 23 2022

Best,
Kun

**Comment by nathanweeks** [comment]
@xiekunwhy : bioconda uses the original exonerate 2.4.0 (see the recipe [meta.yaml](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/exonerate/meta.yaml)), which doesn't include the [selenocysteine patch](https://github.com/nathanweeks/exonerate/commit/329f24d6f08e6e41b6c00649656b80ffa3e72d38). A version of exonerate containing the patch can be built from the master branch of this repo following the instructions in the [README](https://github.com/nathanweeks/exonerate/blob/master/README.md). 

Since the fix is now in the master branch, I'll close this issue, but please do report if you encounter any issues with the functionality.

**Comment by zgh394** [comment]
@grayfall 
hi,do you solve this problem,how to solve it,if you can tell me,i will feel pleasure,thanks

**Comment by zgh394** [comment]
@xiekunwhy hi,do you solve this problem,how to solve it,if you can tell me,i will feel pleasure,thanks
